version: "3.8"
services:
# === extract container ==============================================
  # extract:
  #   build: 
  #     context: ./
  #     dockerfile: ./python1/Dockerfile
  #   volumes:
  #     - ./python1:/app
  #   networks:
  #     - cluster

# === kafka ===========================================================
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - cluster
    # volumes:
    #   - ./vol_kafka:/opt/bitnami/kafka

# === Spark =======
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./spark_entrypoint.sh:/entrypoint.sh
      - ./spark_streaming.py:/opt/bitnami/pyspark_scripts/spark_streaming.py
      - ./vol_spark_checkpoint:/opt/bitnami/pyspark_scripts/checkpoint
    command: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - cluster
  
  spark-worker:
    image: bitnami/spark:3.4.1
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - cluster



# === Cassandra ====================================================================================================
  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    hostname: cassandra
    volumes:
      - ./vol_cassandra_data:/var/lib/cassandra
    ports:
      - 9042:9042
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - cluster

networks:
  cluster:
    